version: "3.4"

services:

  nginx:
    image: nginx
    networks:
      - web
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        com.envisageinternational.desc: "Nginx Service"
    volumes:
      - ./public_html:/var/www/html
    configs:
      - source: mysite
        target: /etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php
      - db
    labels:
      com.envisageinternational.desc: "Nginx Container"
    command: ['sh','-c',"exec nginx -g 'daemon off;'"]

  db:
    image: mysql
    ports:
      - "3306:3306"
    networks:
      - web
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [ node.role == manager ]
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_pwd
    secrets:
      - db_pwd

  php:
    image: php:5.4-fpm
    networks:
      - web
    depends_on:
      - db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        com.envisageinternational.desc: "PHP-FPM Service"
    ports:
      - "9000:9000"
    volumes:
      - ./public_html:/var/www/html
    labels:
      com.envisageinternational.desc: "PHP-FPM Container"

  php-cli:
    image: php:5.4-cli
    networks:
      - web
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        com.envisageinternational.desc: "PHP-CLI Service"
    volumes:
      - ./public_html:/var/www/html
    labels:
      com.envisageinternational.desc: "PHP-CLI Container"
    command: ['bin/sh', '-c', "sleep infinity"]

networks:
  web:

configs:
  mysite:
    file: ./mysite.conf

secrets:
  db_pwd:
    file: ./root_db_password.txt
