FROM php:8.4-fpm AS phptek_php
RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng-dev \
    && docker-php-ext-install -j$(nproc) iconv mysqli

COPY ../public_html/ /var/www/html

FROM nginx AS phptek_nginx
COPY ../public_html/ /var/www/html
COPY ./mysite.conf /etc/nginx/conf.d/default.conf